server:
  port: 8090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB
user:
  address:
    max-count: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml


